label yuri_exclusive_1:
    scene bg club_day
    with wipeleft_scene
    "I'm really curious to talk to Yuuri a bit more."
    "But at the same time, I'd feel bad for distracting him from reading."
    "I catch a glimpse of the cover of his book."
    "It looks like the same book he gave to me."
    "More than that, he seems to be on the first few pages."
    show yuuri 1f at t11
    y "Ah..."
    "Crap."
    "I think he noticed me staring at him."
    "He sneaks another glance at me and our eyes meet for a split second."
    show yuuri 1s
    "He grins sheepishly at me."
    y "Um... H-Hello."
    mc "Sorry!"
    mc "I was just spacing out."
    "I mutter this, sensing I've made us both uncomfortable."
    y 1c "Oh...it's fine."
    y 3j "If I was focused, I wouldn't have noticed in the first place."
    y 1b "I'm just re-reading some of this."
    mc "That's the book you gave me, right?"
    y 1d "That's right."
    y "I'm just refreshing my memory by looking through the first few pages again."
    y "Once it starts to pick up, it's impossible to put down."
    y "It's a very engaging story."
    mc "Oh yeah?"
    mc "Is it a horror book?"
    y "It is."
    mc "Cool. What's it about?"
    y 1h "Well..."
    "Yuuri closes the book and flips it over, scanning his eyes over the back."
    "The book is titled \"Wendigo Soul.\""
    "There's a set of red fangs engraved on the front cover."
    y 1f "Okay."
    y 1a "I just wanted to make sure I don't accidentally give away any spoilers."
    y 3l "Basically, it's about this group of teenagers in the Old West..."
    mc "...A horror story set in the Old West?"
    mc "That's..."
    "...Kind of a weird concept."
    "Yuuri snickers softly."
    y 1d "I thought it was interesting too."
    y 3b "See, the protagonists are the sons of the local cattle barons."
    y "Their lives are difficult enough just trying to survive."
    y 3f "But things get strange when suddenly, people from the town start going missing, and cattle are being viciously mauled in the night by strange, ferocious creatures."
    y "As the story goes on, the friendships of the protagonists start to weaken as they struggle with who to trust among them."
    y 3h "Things only get worse when they suspect the killings relate directly to a mysterious girl who lives alone in the woods."
    mc "That actually sounds pretty cool."
    mc "I wouldn't say it sounds particularly scary, though."
    y 1u "Well...I didn't want to explain it in a way that made it sound off-putting."
    y 1s "Especially if you're not into that sort of thing."
    mc "But I am, actually."
    mc "I love scary video games."
    mc "I'm sure a spooky book would keep my attention."
    y 1c "I'm glad to hear that."
    y 1d "Nothing keeps my attention quite like a spine-tingling story."
    "I keep forgetting Yuuri is into macabre stuff."
    "He's so quiet, polite and gentlemanly on the outside, but his mind seems to be completely different."
    y 3b "See, stories like this challenge you to look at life from a whole new perspective."
    y 3f "When horrible things happen, people are quick to point the finger at the outcast and label them the villain."
    y "It's easy to fear what one doesn't understand, after all."
    y 3h "Then suddenly, when you thought you sided with the protagonist..."
    y 3k "You realize that your supposed 'hero' is more selfish, flawed and ignorant than the perceived villain."
    mc "Ah, one of those stories that make you realize the bad guy had a point the whole time."
    y 6b "Precisely."
    y 4j "It's that kind of moral ambiguity that truly allows the reader to interpret the lesson in their own way."
    y 4m "Making the villain more relatable than the protagonist really forces your mind to explore a very different perspective than it normally would."
    y 4b "It even makes you question the very definition of good versus evil."
    mc "Haha! You're really into this, aren't you?"
    show yuuri 6u
    "Yuuri looks away, blushing."
    "He smiles coyly."
    y 6j "[player]..."
    y 6q "... I think I should warn you that I have this problem."
    y 4q "When I let things like books and writing fill my thoughts..."
    y 7q "I tend to get a bit too overzealous."
    y 6t "So, I'm sorry if I end up acting strange or if I talk too much."
    mc "Don't sweat it, big guy."
    mc "It just means you're passionate about your reading."
    mc "This is a literature club, after all."
    mc "I can sit here and listen to you talk about reading all day."
    mc "In fact..."
    "He had two copies of the same book."
    "It's obvious what he wants."
    "I reach into my bag and retrieve the colossal compendium."
    mc "I may as well get started on reading it, right?"
    y 7p "Ah!"
    y 6o "That's..."
    y 6v "You needn't feel obligated to do so if you really don't want to."
    y 6t "I don't want you to feel like...I'm forcing you..."
    mc "Nonsense."
    mc "Of course I want to."
    mc "In fact..."
    mc "Why don't we read it together?"
    mc "Can I sit here?"
    "I slide into the seat next to him."
    y 6u "If...that is what you choose..."
    "His apprehension suddenly dissipates and he visibly relaxes."
    y 1m "Of course."
    y 1q "I'd pull the seat out for you..."
    y 3c "But they're attached to the desks."
    mc "Haha! It's okay."
    mc "I appreciate the gesture though."
    "Yuuri smiles."
    y 1s "I'm not used to reading in company with someone."
    y 3d "This promises to be a delightful experience."
    "He seems excited to get started."
    mc "Well, I'm not exactly used to it either."
    mc "So let me know if I end up distracting you, okay?"
    y 1b "I'm sure you won't be a problem."
    show yuuri at thide
    hide yuuri
    "I open the book and start the prologue."
    "I soon understand what Yuuri means by reading in company."
    "It's as if I can feel his presence over my shoulder as I read."
    "It's..."
    "Kind of annoying."
    "But at the same time, it's comforting because I know it's him."
    "I suddenly see Yuuri in the corner of my eye."
    "Ah jeez, no wonder it feels like his presence is over my shoulder..."
    "He's like, right there!"
    "I realize he's not actually reading from his own book."
    "He's reading from mine."
    show yuuri 1q at t11
    y "Ah!"
    y "I'm sorry!"
    y 1s "Looks like I'm the one being distracting..."
    y 1u "I'm just..."
    y 1i "I'm having an unusually difficult time staying focused on my own book..."
    "Ah, I see what he's getting at."
    mc "Hahaha! No worries."
    mc "I have an idea."
    "I slide my desk up against Yuuri's and push my book between us."
    mc "This should work, right?"
    y 1b "A very clever solution, indeed."
    show yuuri at thide
    hide yuuri
    "Yuuri timidly closes his copy and places it in his bag."
    "Once we each lean in a little bit, I realize that the big guy really is a bit too big for me to see over."
    "His broad shoulders seem to be blocking me out."
    "Hmm...this is gonna take a little extra thought."
    "I slide my leg under me and prop myself up on my knee, then lean over and rest myself on my elbows."
    "I can see the book now."
    "I just have to make sure I don't lean forward any further, or my chest will be pressed against his arm."
    show yuuri 1f at t11
    y "Are...are you sure you're comfortable like that?"
    mc "I'll be fine."
    mc "You don't mind holding the book, right?"
    y 1c "Not at all."

    #scene y_cg1_base with dissolve_cg
    scene black
    with dissolve_cg
    "Yuuri opens the book."
    "I squint my eyes a bit."
    "It's hard to read that tiny text from so far away."
    "I lean in a bit more, still keeping some space between Yuuri's arm and my chest."
    "But now, we're huddled even closer than before."
    "It's kind of distracting."
    "It's almost as if I can feel the warmth of Yuuri's face and he's in the corner of my vision."
    y "Are you ready?"
    mc "Huh?"
    y "For me to turn the page?"
    mc "Ah!"
    mc "Sorry."
    mc "I didn't know we started."
    "I glance over at Yuuri and our eyes meet."
    "There's no way I'll be able to keep up with him."
    "I'm not exactly a speed-reader."
    y "Ah, that's okay."
    y "I'm sure the small font isn't helping much."
    y "So I don't mind being patient if it takes you a bit longer."
    y "Just let me know when you're ready, okay?"
    mc "Thanks! I appreciate it!"
    "We continue reading."
    "Yuuri no longer asks if I'm ready for him to turn the page."
    "He leaves it open just the right amount of time for me to finish before turning it of his own volition."
    "We continue the first chapter in silence."
    mc "Hey Yuuri..."
    y "Hmm?"
    mc "What's this word mean?"
    "I lean in and point to a word I don't recognize that's being used metaphorically."
    y "Ah... 'effulgent'."
    y "It means shining brightly, or radiant."
    mc "Okay. That makes sense."
    mc "The girlfriend of the main character is all bubbly and cheerful, so it fits."
    y "That's right."
    y "She's a...cute character."
    y "But, I personally prefer the stoic nature of the mysterious girl who lives in the forest."
    mc "There's a shocker."
    y "Oh?"
    y "Am I really that transparent?"
    mc "About as much as a ghost."
    "Yuuri blushes a little."
    y "Well... if I can be completely honest...."
    y "The wild forest girl kind of reminds me of you a little bit."
    mc "Haha! Seriously?"
    y "It's true."
    y "She's blunt, smart, adventurous..."
    y "..And she has a very dry wit about her that I find absolutely charming."
    mc "I see..."
    "I get the feeling that last line wasn't referring directly to the character in the book."
    "I feel my cheeks redden."
    "It's no secret that I like to flirt..."
    "But when someone like Yuuri flirts back..."
    "It's almost more than I can handle."
    y "...!"
    y "Um..."
    y "[player]..."
    mc "Hmm?"
    "I look up curiously at Yuuri."
    "He suddenly looks very embarrassed."
    "What's gotten into him?"
    "My eyes widen as I feel his arm move around a bit beneath me."
    "I look down."
    mc "...!"
    "I must've become too relaxed, because I find myself draped over his arm, leaning on it as though it were a pillow."
    "My chest is resting right against him."
    "I squeal and leap away."
    scene bg club_day
    show yuuri 6q at t11
    mc "Gah!"
    mc "I-I'm sorry!"
    mc "I-I wasn't paying attention!"
    y "It's..."
    y "Ah..."
    y 6u "P-please don't worry about it!"
    y "It's fine!"
    show yuuri at thide
    hide yuuri
    "Keeping his head down, he slowly moves his arm off the desk."
    "I can't decide whose face is redder at this point; mine or his."

    show mateo 4k at t11
    m "Alright, guys!"
    m "Get your poems ready!"
    m 6k "We might not have time if we don't get started now."
    show yuuri 6l at t21
    show mateo at t22
    "Yuuri exhales in relief."
    "I'm kinda relieved too, to be honest."
    "That turned very awkward very quickly."
    show yuuri at t21
    show mateo at f22
    m 6d "Ready, Yuuri?"
    m "I know you probably haven't been looking forward to this."
    m 1d "But at least try."
    show yuuri at f21
    show mateo at t22
    y 6d "Thank you, Mateo."
    y 6g "I'm sure I'll be able to do this."
    show mateo at thide
    show yuuri at t11
    hide mateo
    "Yuuri closes the book and pushes it towards me."
    "It seems he still hasn't recovered fully from our little embarrassing scene."
    "I wonder if he'll feel comfortable enough to read with me again tomorrow."
    mc "I guess I'll do some reading at home tonight."
    y 6i "Yes, that would be best."
    y 6c "It'll be more fun to read together once the story picks up a bit."
    "I smile a little in relief."
    mc "Sound reasoning."
    mc "In that case, I'll finish the first 2 chapters tonight."
    y 1a "Alright."
    show yuuri at thide
    hide yuuri
    "I stand up."
    "I make a mental note of where I left off in the book (which I will absolutely forget later) and slip it back into my bag."
    return

label yuri_exclusive_2:
    $ y_exclusivewatched = True
    play music t6 fadeout 1.0
    scene bg club_day
    with wipeleft_scene
    mc "Hey, Yuri."
    show yuri 2f at t11 zorder 2
    y "Eh?"
    mc "Ah..."
    "I suddenly notice that Yuri is reading a different book from the one we've been reading together."
    mc "Sorry! I didn't mean to interrupt..."
    y 2m "Ah, no..."
    y "I was kind of just waiting for you..."
    show yuri 2a
    mc "Ah, if that's the case..."
label yuri_exclusive_2_ch3:
    mc "Why don't we go ahead and get started?"
    y 2c "Yes, let's!"
    y 3a "Actually, I have a request..."
    y "...Do you mind if I make some tea first?"
    mc "Not at all."
    y 1c "Thanks very much."
    y 1a "If there's one thing that can make my reading time here any better, it's a nice cup of tea."
    y "Not to mention for yourself, as well."
    show yuri at thide zorder 1
    hide yuri
    "Yuri stands up and makes her way to the closet."
    "I follow and watch as she retrieves a small water pitcher from the shelf - the kind with a filter inside."
    show yuri 1f at t11 zorder 2
    y "Can you hold this for a second?"
    mc "Sure..."
    "Yuri hands me the water pitcher and also fetches an electric kettle."
    y "I'm going to plug this in at the teacher's desk, and then we'll go get some water."
    show yuri at thide zorder 1
    hide yuri
    "She walks past me and sets the kettle down on the teacher's desk."
    "I simply watch her movements."
    "To my surprise, the way she moves really contrasts her speaking mannerisms."
    "Especially because of her long legs, Yuri appears elegant and methodical."
    show yuri 1f at t11 zorder 2
    y "Okay, may I have the water pitcher?"
    y 1a "Thanks. I'll be right back."
    mc "Ah, I might as well walk with you..."
    y 1s "Yeah...why not?"
    y "Shall we go, then?"
    mc "Yeah..."
    show monika 2a at l31
    m "Hm? Where are you two off to?"
    show yuri 2e
    mc "Eh?"
    mc "We're just...Yuri was going to make some tea, so..."
    "I suddenly realize how weird it sounds to explain this to Monika."
    mc "We're just filling the water pitcher..."
    show monika at f31 zorder 3
    m "Ah, okay!"
    m 4j "Sorry, I was just a bit curious..."
    m "That's kind of a one-person job, isn't it?"
    show monika 4a at t31 zorder 2
    mc "That's--"
    show yuri at f11 zorder 3
    y 1k "Monika, please mind your own business for once."
    y "Or do you want to tell me there's something wrong with helping involve [player] in club activities?"
    show yuri at t11 zorder 2
    show monika at f31 zorder 3
    m 1g "E-Eh...?"
    show monika at t31 zorder 2
    mc "--!"
    "My mouth gapes."
    show monika at f31 zorder 3
    m 5a "I..."
    m "I suppose there's nothing wrong with that..."
    show monika at t31 zorder 2
    show yuri at f11 zorder 3
    y 2l "Hmph..."
    y "Then let's go, [player]."
    show yuri at t11 zorder 2
    mc "Ah..."
    "Yuri quickly exits the room, and I follow."
    stop music fadeout 1.0
    scene bg corridor
    show yuri 4c at t11 zorder 2
    with wipeleft_scene
    "Once in the hallway, she suddenly puts her forehead against the wall."
    y "I spoke without thinking..."
    y "How could I say something like that...?"
    mc "Yuri..."
    y 4b "I just..."
    y "Something about the way she said that..."
    y "It made me feel so...irritated."
    y "What's wrong with me...?"
    mc "No, Yuri."
    mc "I think...you did the right thing!"
    mc "I wasn't expecting it, but..."
    mc "It's also not right for Monika to judge people like that."
    play music t9
    y 4a "[player]..."
    y "How come even when I do something bad..."
    y "You're being nice to me?"
    mc "Because."
    mc "Nothing that you do is as bad as you make it seem in your head."
    mc "Nobody's perfect."
    mc "We have emotions, and we can't always hide them away."
    mc "But you always amplify things in your head..."
    mc "Your mind turns a light rain shower into a hurricane."
    y 3q "Ah..."
    y "N-No..."
    y "Wouldn't you hate me for something as terrible as that...?"
    mc "Why would I hate you?"
    mc "I can't hate someone for having emotions..."
    mc "What kind of friend would do that?"
    y 4c "Friend...you say?"
    y "Ah...um..."
    "Yuri lifts her head."
    y 3w "[player]..."
    y 3t "I really like...being friends with you!"
    mc "Ahaha..."
    mc "Thanks, Yuri."
    mc "I like being friends with you too..."
    "I feel kind of awkward saying something like that..."
    "But I'm doing my best to help Yuri feel better."
    mc "Anyway...!"
    y 3u "Ah-- Yeah..."
    y "Shall we go?"
    mc "Yeah."
    show yuri at thide zorder 1
    hide yuri
    "Yuri and I walk to the nearest water fountain."
    "Once we fill up the water pitcher, we return to the classroom."
    play music t6 fadeout 1.0
    scene bg club_day
    show yuri 1a at t11 zorder 2
    with wipeleft_scene
    y "[player], do you like oolong tea?"
    mc "Ah, yeah."
    mc "Anything is fine."
    y "Very well."
    "Yuri sets the temperature on the kettle to 200 degrees."
    y 1f "Now it's time to get the teapot."
    mc "You really do this properly, don't you?"
    y 1u "Of course..."
    y "I shouldn't do any less when I'm making tea for others."
    mc "Even if I'm not an expert on tea or anything...?"
    y 2m "Huhu."
    y 2a "In that case, you'll only be even more impressed."
    mc "Ah...perhaps I will!"
    show yuri at thide zorder 1
    hide yuri
    "Yuri fetches the teapot and begins measuring the tea leaves."
    "To my surprise, she even starts humming a little to herself."
    show yuri 1c at t11 zorder 2
    mc "You must be in a good mood now..."
    y 1a "Is that so?"
    y "I was letting it show..."
    y "And you noticed."
    y 2u "I was doing a bit of thinking..."
    y "And I decided that I would try expressing myself a little bit more."
    y "It turns out it's not very hard for me to do..."
    y 1c "When it's you who's around, anyway."
    mc "Ah..."
    mc "That's great, Yuri!"
    mc "Just don't push yourself too much."
    y 3u "You're always worrying about me, [player]..."
    y "It's very endearing."
    mc "That's..."
    "Yuri wasn't kidding..."
    "I don't even know if I can keep up with this...!"
    "I watch Yuri pour a cup of tea for each of us."
    y 1a "[player], I have another request."
    y "Do you mind if we sit on the floor today?"
    mc "Eh? Why's that?"
    y 1h "It's a little bit easier on my back..."
    y "I can read with my back against the wall rather than bending over at my desk."
    mc "Ah, sorry, I didn't realize."
    y 1a "No worries."
    y "I just have back pain fairly regularly, so I do my best to manage it."
    mc "Is that so?"
    mc "I wonder why that is..."
    y 1f "It's most likely because my--"
    y 1n "Ah--"
    y 1o "M-My..."
    mc "Your posture, right?"
    mc "Always hunched over like that while reading..."
    y 2p "Yes!"
    y 2q "I have terrible reading posture!"
    y "So that's why we should sit on the floor."
    mc "Fair enough."
    mc "I'll go ahead and get the book."
    show yuri at thide zorder 1
    hide yuri
    "I retrieve the book from my bag."
    mc "Ah, I have some chocolate as well..."
    "It's a bag of small chocolate candies that I kept hidden from Sayori's candy radar."
    "I take it, since it'll go well with the tea."
    "Yuri and I then sit against the wall, teacups at our sides."
    "As if in sync, we assume the same reading position as last time, each holding one half of the book."
    "Except this time..."
    "Our bodies are even closer to each other."
    show yuri 2h at t11 zorder 2
    y "I can't see too well..."
    mc "--!"
    show yuri 2e at d11
    "Yuri slides closer until our shoulders are touching."
    "How am I supposed to focus on reading like this...?!"
    "Yuri was always kind of cute, but..."
    "When she's being less apprehensive, it's almost more than I can handle!"
    y 2f "Your teacup..."
    "Yuri hands me my teacup."
    "Holding it with my hand that's not holding the book, I end up in a position that makes it even harder to focus."
    "Because now I need to worry about making sure I don't accidentally touch her chest...!"
    "Meanwhile, Yuri hasn't noticed a single thing."
    "She wears her intense reading expression, and I can only presume the world around her has faded away."
    "I use all of my willpower to focus on reading."
    "..."
    "After a few minutes, I finally manage to relax a little."
    "I put the teacup between my legs and fumble with the chocolate wrapper."
    mc "Ah, sorry..."
    "I briefly let go of the book to finish opening the wrapper."
    mc "You can have as much as you want."
    y 2s "Ah, that's..."
    y "That's okay, I won't take any..."
    mc "Eh? Are you sure?"
    y 2v "Well..."
    y "If I touch it, then it might get smudges on the pages..."
    mc "Ah, you're right..."
    mc "I didn't even think about that."
    mc "My bad..."
    y 2a "No need to apologize."
    y "I'll hold the book, okay?"
    mc "Are you sure...?"
    y "Of course."
    $ persistent.clear[3] = True
    scene y_cg2_bg
    show y_cg2_base
    show y_cg2_details
    show y_cg2_nochoc
    show y_cg2_dust1
    show y_cg2_dust2
    show y_cg2_dust3
    show y_cg2_dust4
    with dissolve_cg
    "Yuri opens the book with both hands."
    "She holds it so that I don't have any harder of a time reading from it."
    "But as a result, her left arm is practically resting on top of my leg."
    mc "Well, in that case..."
    "Yuri is already totally focused on reading again."
    "I take a chocolate candy and pop it into my mouth."
    "Then, I take another chocolate..."
    "And I hold it up to Yuri."
    "She doesn't even look away from the book."
    "She simply parts her lips, as if this situation was completely natural."
    "But that means I can't stop here!"
    hide y_cg2_nochoc
    "I apprehensively place the chocolate in her mouth."
    "Just like that, Yuri closes her lips over it."
    y "Eh...?"
    show y_cg2_exp2
    "Yuri's expression suddenly breaks."
    y "Did..."
    y "Did I just..."
    "Yuri looks at me like she needs to confirm what just happened."
    show y_cg2_exp3
    show y_cg2_nochoc:
        alpha 0
        linear 0.5 alpha 1
    hide y_cg2_exp2
    y "U-Um..."
    y "[player]..."
    mc "S-Sorry!"
    mc "I guess I shouldn't have done that..."
    y "Ah, that's..."
    y "Well..."
    y "Y-You were just helping..."
    y "That's something that...friends do..."
    y "...Right?"
    mc "I mean..."
    "Not really in this kind of context, but..."
    mc "Yeah..."
    mc "...That's all it was."
    y "Yeah..."
    y "Then..."
    y "You don't need to stop or anything..."
    mc "I-I see..."
    hide y_cg2_exp3
    "The situation has gotten really tense..."
    "Yuri tries to return to the book."
    "But I can tell just by her expression that even she can't focus now."
    "My heart is pounding..."
    "I nervously take another chocolate between my fingers."
    "But this time, Yuri's eyes meet mine."
    show y_cg2_exp3
    y "..."
    "How did it even come to this...?"
    "Yuri doesn't avert her gaze."
    "I notice her chest rising and falling to the rhythm of her breaths."
    "I raise my arm..."
    y "Ah..."
    "Like before, Yuri parts her lips."
    "But...it's different this time."
    hide y_cg2_nochoc
    "I take the chocolate and place it in her mouth."
    "I feel her hot breath on my fingers."
    stop music
    window hide(None)
    scene bg club_day
    window show(None)
    window auto
    show monika 4b at l31 zorder 2
    m "Okay, everyone!"
    mc "Uwa--"
    show yuri 3p at t11 zorder 2
    y "A-Ah!"
    play music t3
    "Yuri jolts back."
    show yuri 3n
    show monika at f31 zorder 3
    m "It's time to share poems!"
    m "[player], you can help Yuri put away the tea stuff, right?"
    show monika at t31 zorder 2
    mc "Y-Yeah...of course."
    show monika at f31 zorder 3
    m "Okay, thanks!"
    show monika at thide zorder 1
    hide monika
    "The spell is abruptly broken."
    y 4c "I'll..."
    y "I'll take care of the cups..."
    mc "Yeah..."
    show yuri at thide zorder 1
    hide yuri
    "Yuri picks up the teacups from the floor."
    "I pick up the bag of chocolates."
    "In the end, we hastily clean up without so much as a word between us."
    "I get the feeling this is something neither of us will have the courage to bring up..."
    return
